export const STORE_STATE_DATA = 'STORE_STATE_DATA';
export const STORE_TESTING_DATA = 'STORE_TESTING_DATA';
export const STORE_HOSPITAL_DATA = 'STORE_HOSPITAL_DATA';
export const STORE_HELPLINE_DATA = 'STORE_HELPLINE DATA';
export const STORE_NOTIFICATION_DATA = 'STORE_NOTIFICATION_DATA';